FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12-run

ENV PULSE_SERVER=unix:/run/pulse/pulseaudio.socket
ENV PULSE_SINK=alsa_output.default

# Install dependencies for pulseaudio2 node package
RUN install_packages python pkg-config make g++ libpulse-dev libasound2-dev mplayer vim tmux

WORKDIR /usr/src

RUN curl https://www.kozco.com/tech/LRMonoPhase4.wav --silent --output test.wav

COPY package.json ./
RUN JOBS=MAX npm install --production
COPY build ./

CMD [ "node", "server.js" ]